// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Gozen.Data.Migrations.GozenDBMigrations
{
    [DbContext(typeof(GozenDbContext))]
    [Migration("20210506211948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gozen.Data.Tables.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 886, DateTimeKind.Utc).AddTicks(4350),
                            Type = "Pasaport"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 886, DateTimeKind.Utc).AddTicks(7177),
                            Type = "Visa"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 886, DateTimeKind.Utc).AddTicks(7192),
                            Type = "Travel"
                        });
                });

            modelBuilder.Entity("Gozen.Data.Tables.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentNumber")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("Passenger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentNumber = 1111,
                            DocumentTypeId = 1,
                            Gender = 0,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 908, DateTimeKind.Utc).AddTicks(7513),
                            Name = "Name_1",
                            Surname = "Surname_1"
                        },
                        new
                        {
                            Id = 2,
                            DocumentNumber = 2222,
                            DocumentTypeId = 2,
                            Gender = 1,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 909, DateTimeKind.Utc).AddTicks(3323),
                            Name = "Name_2",
                            Surname = "Surname_2"
                        },
                        new
                        {
                            Id = 3,
                            DocumentNumber = 3333,
                            DocumentTypeId = 3,
                            Gender = 0,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 909, DateTimeKind.Utc).AddTicks(3338),
                            Name = "Name_3",
                            Surname = "Surname_3"
                        },
                        new
                        {
                            Id = 4,
                            DocumentNumber = 4444,
                            DocumentTypeId = 1,
                            Gender = 1,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 909, DateTimeKind.Utc).AddTicks(3343),
                            Name = "Name_4",
                            Surname = "Surname_4"
                        },
                        new
                        {
                            Id = 5,
                            DocumentNumber = 5555,
                            DocumentTypeId = 2,
                            Gender = 0,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 909, DateTimeKind.Utc).AddTicks(3346),
                            Name = "Name_5",
                            Surname = "Surname_5"
                        },
                        new
                        {
                            Id = 6,
                            DocumentNumber = 6666,
                            DocumentTypeId = 3,
                            Gender = 1,
                            IsActive = true,
                            IssueDate = new DateTime(2021, 5, 6, 21, 19, 47, 909, DateTimeKind.Utc).AddTicks(3349),
                            Name = "Name_6",
                            Surname = "Surname_6"
                        });
                });

            modelBuilder.Entity("Gozen.Data.Tables.Passenger", b =>
                {
                    b.HasOne("Gozen.Data.Tables.DocumentType", "DocumentType")
                        .WithMany("Passenger")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Gozen.Data.Tables.DocumentType", b =>
                {
                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
